/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ss2;

import java.util.regex.*;
import java.util.*;
import javax.swing.JComboBox;
import java.sql.*;

/**
 *
 * @author choco
 */
public class panelClass extends javax.swing.JPanel {

    static Set<ClassStudent> newClass = new HashSet<ClassStudent>();
    Set<String> listIdClass = new HashSet<String>();

    /**
     * Creates new form Class
     */
    public panelClass() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertClassPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        listClass = new javax.swing.JComboBox<>();
        viewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainView = new javax.swing.JTextArea();
        alertAdd = new javax.swing.JLabel();
        alertView = new javax.swing.JLabel();
        export = new javax.swing.JButton();

        InsertClassPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                InsertClassPanelComponentHidden(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VIEW CLASS");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));

        jLabel3.setText("Name:");

        jLabel4.setText("Id:");

        jLabel5.setText("Code:");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Code:");

        listClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClassActionPerformed(evt);
            }
        });

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        mainView.setColumns(20);
        mainView.setRows(5);
        jScrollPane1.setViewportView(mainView);

        export.setText("Export All");

        javax.swing.GroupLayout InsertClassPanelLayout = new javax.swing.GroupLayout(InsertClassPanel);
        InsertClassPanel.setLayout(InsertClassPanelLayout);
        InsertClassPanelLayout.setHorizontalGroup(
            InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertClassPanelLayout.createSequentialGroup()
                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InsertClassPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(InsertClassPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InsertClassPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(InsertClassPanelLayout.createSequentialGroup()
                                        .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(listClass, 0, 286, Short.MAX_VALUE)
                                            .addComponent(alertView, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(export, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(viewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jScrollPane1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InsertClassPanelLayout.createSequentialGroup()
                                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(InsertClassPanelLayout.createSequentialGroup()
                                        .addComponent(alertAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(code, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addGap(16, 16, 16))
        );
        InsertClassPanelLayout.setVerticalGroup(
            InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertClassPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton)
                    .addComponent(alertAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(listClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alertView, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(export))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertClassPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InsertClassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        int ck = 0;
        Integer idClass = 0;
        String nameClass = "";
        String codeClass = "";

        if (isNumber(id.getText()) && !(listIdClass.contains(id.getText()))) {

            idClass = Integer.parseInt(id.getText());
            ck += 1;

        }
        nameClass = name.getText();
        codeClass = code.getText();
        if (ck == 1) {
            listIdClass.add(id.getText());
            ClassStudent newRecord = new ClassStudent(idClass, nameClass, codeClass);
            newClass.add(newRecord);
            alertAdd.setText("Add complete");
            formatCombobx(listClass);
            alertAdd.setText("");
            alertView.setText("");
            id.setText("");;
            name.setText("");
            code.setText("");
        } else {

            alertAdd.setText("Id ms be Integer and don't duplicate");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void formatCombobx(JComboBox list) {
        list.removeAllItems();
        list.addItem("Select Class");
        for (ClassStudent lts : panelClass.newClass) {
            list.addItem(lts.getCode().toString());
        }

    }

    private boolean isNumber(String a) {
        String regex_number = "[0-9]+";
        if (Pattern.matches(regex_number, a)) {
            if (Integer.parseInt(a) > 0) {
                return true;
            }
        }
        return false;
    }
    private void listClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClassActionPerformed

    }//GEN-LAST:event_listClassActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        //hoi thay cho nay
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/test1", "root", "");
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM class");
            String str = "";
            while (rs.next()) {
                Integer idClass = rs.getInt(1);
                String nameClass = rs.getString(2);

                String codeClass = rs.getString(3);

                str += "ID: " + idClass + " Name: " + nameClass + " Code: " + codeClass;

            }
            mainView.setText(str);
        } catch (Exception e) {
            e.printStackTrace();
        }
//code cu
//        if (newClass.size() == 0) {
//            alertView.setText("Please Add class first!");
//        } else {
//
//            String idClassC = listClass.getSelectedItem().toString();
//            String str = "";
//            if (idClassC.equals("Select Class")) {
//                alertView.setText("Please choose another Item!");
//            } else if (idClassC.equals("All")) {
//                alertView.setText("");
//
//                for (ClassStudent lts : newClass) {
//
//                    str += "ID: " + lts.getId() + " Name: " + lts.getName() + " Code: " + lts.getCode() + "\n";
//                }
//                mainView.setText(str);
//            } else {
//                alertView.setText("");
//                String k = idClassC;
//
//                for (ClassStudent lts : newClass) {
//                    if (lts.getCode().equals(k)) {
//                        str += "ID: " + lts.getId() + " Name: " + lts.getName() + " Code: " + lts.getCode();
//                    }
//                }
//                mainView.setText(str);
//            }
//        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void InsertClassPanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_InsertClassPanelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertClassPanelComponentHidden

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InsertClassPanel;
    private javax.swing.JLabel alertAdd;
    private javax.swing.JLabel alertView;
    private javax.swing.JTextField code;
    private javax.swing.JButton export;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listClass;
    private javax.swing.JTextArea mainView;
    private javax.swing.JTextField name;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
